### ISSUE TITLE
What went wrong?

### ISSUE THREAD

**Issue by nardev** [devxpy/thinkfan-control-gui#2]
File "fan.py", line 16
    result.append(f'Core {count}: ' + i.split(':')[-1].split('(')[0].strip())
                                  ^
SyntaxError: invalid syntax

**Comment by devxpy** [comment]
Please install python3.6+.

Also, search the existing issues before making a new one! (https://github.com/devxpy/thinkfan-control-gui/issues/1)

**Comment by devxpy** [comment]
Fixed in https://github.com/devxpy/thinkfan-control-gui/commit/a7e40255902589a20deef9094702f77a6ea2cc87 anyway ...
